#!/bin/bash        

for DIR in *; do
    if [[ -d $DIR ]]; then
		cd $DIR
		rm -rf build
		mkdir build
		cd build
		echo "************************************ MAKING" $DIR "DEMO"
		cmake ..
		cd ../..
    fi
done


            


